################################################################################
# Docker Compose file for starting up the service for testing in GitHub workflow
# This template provides comparable infrastructure to the real environment.
#   - mongodb
#   - redis
#   - localstack (s3, sqs, sns)
#
# Both mongo and localstack have init scripts included for setting up resources
# on startup. These scripts are in docker/scripts.
#
# It also includes a selenium-chrome container for running the browser headless.
#
# The services being tested can either be started up here using the latest
# builds from dockerhub.
# In the example each service has a .env config file in docker/config/
# Services can reference each other by their container names.
# e.g. http://cdp-example-node-backend:3001/
#
################################################################################
services:
  ################################################################################
  # Headless browser, used by the test suite to actually run the tests against the
  # containers.
  selenium-chrome:
    image: selenium/standalone-chrome:dev
    platform: linux/amd64
    ports:
      - 4444:4444

  localstack:
    image: localstack/localstack:3.2.0
    environment:
      - LOCALSTACK_HOST=127.0.0.1
      - SERVICES=s3,sqs,sns,dynamodb
      - LS_LOG=WARN
    env_file:
      - ./docker/config/defaults.env
    volumes:
      - ./docker/scripts/localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: ['CMD', 'curl', 'localhost:4566']
      interval: 5s
      start_period: 5s
      retries: 3

  ################################################################################
  redis:
    image: redis:7
    ports:
      - '6379:6379'
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', 'PING']
      interval: 5s
      start_period: 2s
      retries: 5
    networks:
      - cdp-tenant

  mongodb:
    image: mongo:6.0.13
    networks:
      - cdp-tenant
    ports:
      - '27017:27017'
    healthcheck:
      test: ['CMD', 'mongosh', '--eval', 'db.adminCommand("ping")']
      interval: 5s
      start_period: 5s
      retries: 5

    volumes:
      - mongodb-data:/data
    restart: always
  ################################################################################
  #
  # Add the services you want to test below.
  #
  ################################################################################
  epr-register-enrol-frontend:
    image: defradigital/epr-register-enrol-frontend:${EPR_REGISTER_ENROL_FRONTEND:-latest}
    environment:
      - PORT=3000
      - API_BASE_URL='http://epr-register-enrol-backend:8080'
    depends_on:
      epr-register-enrol-backend:
        condition: service_started
      redis:
        condition: service_healthy
    ports:
      - 3000:3000
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:3000/health']
      interval: 3s
      start_period: 2s
      retries: 3
  ################################################################################
  epr-register-enrol-backend:
    image: defradigital/epr-register-enrol-backend:${EPR_REGISTER_ENROL_BACKEND:-latest}
    environment:
      - PORT=8080
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 8080:8080
    healthcheck:
      test: ['CMD', 'curl', 'http://localhost:8080/health']
      interval: 3s
      start_period: 2s
      retries: 3

volumes:
  mongodb-data:

networks:
  cdp-tenant:
    driver: bridge
